import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import Router from "next/router";

import image1 from "../assets/background_1.jpeg";
import image2 from "../assets/background_2.jpeg";
import image3 from "../assets/background_3.jpeg";
import image4 from "../assets/background_4.jpeg";

import agricultura1 from "../lotties/agricultura1.json";
// import Swiper core and required modules
import {
  Navigation,
  Pagination,
  Scrollbar,
  A11y,
  Autoplay,
  EffectCoverflow,
} from "swiper";

import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import { useEffect, useState } from "react";
import api from "../api";

type Data = {
  nome: string;
  descricao: string;
  codigo: string;
  preco: number;
  imagem: string;
};

const Home = () => {
  const [produtos, setProdutos] = useState([]);
  const defaultOptions = {
    loop: true,
    autoplay: true,
    animationData: agricultura1,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice",
    },
  };

  useEffect(() => {
    const getProdsDestaque = async () => {
      const { data } = await api.get("/produto/destaque");

      setProdutos(data);
    };
    getProdsDestaque();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Jr. Agropeças</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <div className={styles.containerApresetation}>
          <div className={styles.containerApresetation__text}>
            <Swiper
              modules={[Navigation, Pagination, Scrollbar, A11y, Autoplay]}
              spaceBetween={50}
              slidesPerView={1}
              autoplay={{ delay: 2500, disableOnInteraction: false }}
              onSwiper={(swiper) => console.log(swiper)}
              onSlideChange={() => console.log("slide change")}
            >
              <SwiperSlide>
                <div className={styles.container_slide}>
                  <div className={styles.container_text_slide}>
                    <h1>Jr. Agropeças</h1>
                    <p>
                      Somos Auto Jr. Agro Peças e o nosso negócio é vender peças
                      agrícolas e prestar serviços de prensagem de mangueiras
                      hidráulicas.
                    </p>
                  </div>
                  <div className={styles.imagem_container_slide}>
                    <div className={styles.image_mask}></div>
                    <div className={styles.content_image}>
                      <Image
                        alt="image_ilustration"
                        src={image1}
                        layout="fill"
                      />
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className={styles.container_slide}>
                  <div className={styles.container_text_slide}>
                    <h1>Jr. Agropeças</h1>
                    <p>
                      Somos Auto Jr. Agro Peças e o nosso negócio é vender peças
                      agrícolas e prestar serviços de prensagem de mangueiras
                      hidráulicas.
                    </p>
                  </div>
                  <div className={styles.imagem_container_slide}>
                    <div className={styles.image_mask}></div>
                    <div className={styles.content_image}>
                      <Image
                        alt="image_ilustration"
                        src={image2}
                        layout="fill"
                      />
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className={styles.container_slide}>
                  <div className={styles.container_text_slide}>
                    <h1>Jr. Agropeças</h1>
                    <p>
                      Somos Auto Jr. Agro Peças e o nosso negócio é vender peças
                      agrícolas e prestar serviços de prensagem de mangueiras
                      hidráulicas.
                    </p>
                  </div>
                  <div className={styles.imagem_container_slide}>
                    <div className={styles.image_mask}></div>
                    <div className={styles.content_image}>
                      <Image
                        alt="image_ilustration"
                        src={image3}
                        layout="fill"
                      />
                    </div>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide>
                <div className={styles.container_slide}>
                  <div className={styles.container_text_slide}>
                    <h1>Jr. Agropeças</h1>
                    <p>
                      Somos Auto Jr. Agro Peças e o nosso negócio é vender peças
                      agrícolas e prestar serviços de prensagem de mangueiras
                      hidráulicas.
                    </p>
                  </div>
                  <div className={styles.imagem_container_slide}>
                    <div className={styles.image_mask}></div>
                    <div className={styles.content_image}>
                      <Image
                        alt="image_ilustration"
                        src={image4}
                        layout="fill"
                      />
                    </div>
                  </div>
                </div>
              </SwiperSlide>
            </Swiper>
          </div>
          <div className={styles.containerApresetation__image}>
            {/*   <Lottie 
            options={defaultOptions}
              height={400}
              width={400}
          /> */}
          </div>
        </div>

        <div className={styles.linha_de_produtos}>
          <div className={styles.linha_de_produtos__text}>
            <h3>Produtos em destaque</h3>
          </div>
        </div>
        <div className={styles.containerProdutos}>
          <div className={styles.contentContainerProdutos}>
            <div className={styles.contentProdutos}>
              {produtos.map((produto: any, key) => {
                return (
                  <div
                    className={styles.contentProduto}
                    key={key}
                    onClick={() => {
                      //envio para a pagina de visualizar produto com a query produto.id
                      Router.push({
                        pathname: "/visualizarProduto",
                        query: { id: produto.id },
                      });
                    }}
                  >
                    <div className={styles.imageProduto}>
                      <Image
                        src={
                          produto.uploads[0]?.url ||
                          "https://via.placeholder.com/300x300"
                        }
                        width={200}
                        height={200}
                        alt="produto"
                      />
                    </div>
                    <div className={styles.informationsProduto}>
                      <p>{produto.descricao || "Produto sem nome"}</p>
                      {/* <p>{produto.descricao}</p> */}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
